# Generated by Django 4.0.6 on 2022-08-23 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_appuser_img1_alter_appuser_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='img1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='头像'),
        ),
    ]
